# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: nZUV6vai1fbAkLoqbP2ali
      POSTGRES_USER: agilepoker-db

  cache_db:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
